name: 'update nextstrain.org/search from latest datasets in s3'

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # "At 01:00 UTC on every day-of-week from Tuesday through Saturday. 
    # This works out to 17:00 Monday-Friday Pacific Time, i.e. the time
    # by which the ncov build has usually been published to s3 when it
    # is being run by folks in Seattle. When it is being run by folks
    # in Switzerland, ncov build data is usually published by 16:00 UTC,
    # so this update will lag behind that by ~9 hours. It can also be
    # triggered from the command line at any time with a respository_dispatch (below)."
    - cron:  '0 1 * * TUE-SAT'
  workflow_dispatch:

jobs:
  update-search:
    if: github.repository == 'nextstrain/nextstrain.org'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm ci
    - uses: nextstrain/.github/actions/setup-nextstrain-cli@master
    # configure AWS necessary for `collect-search-results.js` and `nextstrain remote upload`
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - run: aws sts get-caller-identity
    - name: update sars-cov-2 search
      run: |
        ./scripts/collect-search-results.js --pathogen sars-cov-2
        nextstrain remote upload s3://nextstrain-data ./data/search_sars-cov-2.json
